# Generated by Django 5.1.1 on 2025-03-16 14:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subvariant',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subvariant',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hsn_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_stock',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='variant',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.CreateModel(
            name='ProductVariantItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_code', models.CharField(db_index=True, max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hsn_code', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products_app.product')),
            ],
            options={
                'db_table': 'product_items',
            },
        ),
        migrations.CreateModel(
            name='VariantOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option', models.CharField(db_index=True, max_length=255)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products_app.variant')),
            ],
            options={
                'db_table': 'variant_options',
                'unique_together': {('variant', 'option')},
            },
        ),
        migrations.CreateModel(
            name='ProductConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='products_app.productvariantitem')),
                ('variant_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='products_app.variantoption')),
            ],
            options={
                'db_table': 'product_configurations',
                'unique_together': {('product_item', 'variant_option')},
            },
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
        migrations.DeleteModel(
            name='SubVariant',
        ),
    ]
