# Generated by Django 5.1.1 on 2025-03-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_alter_subvariant_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productvariantitem',
            table='product_variant_items',
        ),
    ]
