# Generated by Django 5.1.1 on 2025-03-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0003_alter_productvariantitem_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_stock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
