# Generated by Django 5.1.7 on 2025-03-26 19:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0005_product_hsn_code_alter_product_product_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LowStockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_notified', models.DateTimeField(blank=True, null=True)),
                ('product_variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products_app.productvariantitem')),
            ],
            options={
                'db_table': 'low_stock_alerts',
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('add', 'Stock Addition'), ('remove', 'Stock Removal'), ('adjustment', 'Stock Adjustment')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=255, null=True)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='products_app.productvariantitem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stock Transactions',
                'db_table': 'stock_transactions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
